create database customer_behaviour;
use customer_behaviour;
select * from customer;
--  Business Questions
-- 1) What is the total revenue generated by male vs female customers
select gender,sum(purchase_amount) as Total_Revenue
from customer
group by gender;
-- 2) Which customers used discount but still spend more than the average purches amount
select customer_id,purchase_amount
from customer
where discount_applied="yes" and purchase_amount>=
(select avg(purchase_amount) from customer);
-- 3) Which of the top 5 products wjth highest average review ratings
select item_purchased,round(avg(review_rating),2) as Average_Product_Rating
from customer
group by item_purchased
order by Average_Product_Rating desc
limit 5;
-- 4) Comapre the average purches amount between standart and express shipping
select * from customer;
select shipping_type,round(avg(purchase_amount),2) as Average_Purches_Amount
from customer
group by shipping_type
having shipping_type in('standard','express');
 -- 5) Do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers
 select subscription_status,
count(*) As Total_Customers ,
round(avg(purchase_amount),2) Avg_Spend,
round(sum(purchase_amount),2) as Total_revenue
 from customer 
 group by subscription_status
 order by Avg_Spend,Total_revenue desc;
 -- 6) Which 5 Products  have the highest percentage of purchases with discount applied?
 select * from customer;
 select item_purchased,
 round(100* sum(case  when discount_applied="yes" then 1 else 0 end)/count(*),2) as discount_rate
 from customer
 group by item_purchased
 order by discount_rate desc
 limit 5;
 -- 7) Segment customers into new,returning,and loyal based on their total number of 
 -- privious purchase and, show the count of each segment.
with customer_type as 
(select customer_id,previous_purchases,
case 
when previous_purchases =1 then "New"
when previous_purchases between 2 and 10 then "Returning"
else "Loyal"
end as Customer_Segment
from customer)
select Customer_Segment,
count(Customer_Segment) as Number_Of_Customers
from customer_type
group by Customer_Segment;
--  8)What are the top 3 most purchesed products within each category?
select * from customer;
with Top_Products as
(select item_purchased,category,count(customer_id) As Total_Orders,
row_number() over(partition by category order by count(customer_id) desc) as Item_rank
from customer
group by item_purchased,category)
select category,item_purchased,Total_Orders,Item_rank
from Top_Products 
where Item_rank <=3;
-- 9) Are customer who are repeat buyers (more than 5 previous purchas) also likely to subscribe?
select * from customer;
select subscription_status,count(customer_id) as Repeat_buyers
from customer
where previous_purchases >5
group by subscription_status;
-- 10) What is the revnue contributuion of age groups 
select * from customer;
select age_group,
sum(purchase_amount) as Total_Revenue
from customer
group by age_group
order by Total_Revenue desc;
